### PR TITLE
Feature/variance control

### PR DESCRIPTION
**Pull request by szuecs**
I don't like the package global variable, but I also don't like to change the signature.
Any idea to do this better or is it good enough?

### CODE REVIEW

**Comment by Raffo** [comment]
I have no big problem with the variable being something like that, honestly.

**Comment by Raffo** [comment]
LGTM

**Comment by Raffo** [comment]
👍

**Comment by Raffo** [comment]
👍

**Comment by Raffo** [comment]
👍

**Comment by szuecs** [comment]
zappr!

**Comment by njuettner** [comment]
:+1:

**Comment by njuettner** [comment]
:+1:

**Comment by Raffo** [comment]
👍

**Comment by njuettner** [comment]
:+1:

**Pull request merged**
