### PR TITLE
GitHub OAuth2

### PR DESCRIPTION
**Pull request by njuettner**
#37 GitHub OAuth2 Implementation

### CODE REVIEW

**Comment by szuecs** [comment]
Thanks @njuettner for the PR.
Can you create a REDME.md section for github OAuth2 similar to the google section?
And please fix the build https://github.com/zalando/gin-oauth2/pull/40 should do it.

**Comment by njuettner** [comment]
Thanks for looking at it. I've added the section how to use GitHub in README.

**Comment by szuecs** [comment]
:+1:

**Comment by njuettner** [comment]
👍

**Pull request merged**
